const signs=[
{id:"aries",name:"Aries",glyph:"♈",dates:"MAR 21 — APR 19",element:"FIRE · CARDINAL",title:"Fire Meets Moving Water",trait:"decisive energy",lesson:"Let commitment begin after observation, not before it.",mantra:{bondi:"Pause for two sets before moving.",byron:"Choose one peak and commit."},theme:["#ff785a","#f3b0a1","rgba(255,120,90,.20)"],layout:"solar"},
{id:"taurus",name:"Taurus",glyph:"♉",dates:"APR 20 — MAY 20",element:"EARTH · FIXED",title:"Wait for the True Line",trait:"patient rhythm",lesson:"Quality will matter more than wave count today.",mantra:{bondi:"Wait for the wave with real shape.",byron:"Settle into the rhythm."},theme:["#9ccf8e","#c7dfbd","rgba(156,207,142,.18)"],layout:"earth"},
{id:"gemini",name:"Gemini",glyph:"♊",dates:"MAY 21 — JUN 20",element:"AIR · MUTABLE",title:"One Choice Among Many",trait:"quick adaptability",lesson:"Read changing peaks without scattering your attention.",mantra:{bondi:"Watch how the peak shifts.",byron:"Let curiosity choose one clear line."},theme:["#f0cc62","#f5dfa0","rgba(240,204,98,.18)"],layout:"split"},
{id:"cancer",name:"Cancer",glyph:"♋",dates:"JUN 21 — JUL 22",element:"WATER · CARDINAL",title:"Let the Water Speak",trait:"strong intuition",lesson:"Sensitivity becomes power when it turns into careful observation.",mantra:{bondi:"Trust the pattern you notice.",byron:"Take a quiet shoreline read."},theme:["#8ed0df","#c2e4ec","rgba(142,208,223,.18)"],layout:"lunar"},
{id:"leo",name:"Leo",glyph:"♌",dates:"JUL 23 — AUG 22",element:"FIRE · FIXED",title:"Confidence Without Performance",trait:"warm confidence",lesson:"The best line needs presence, not performance.",mantra:{bondi:"Surf one wave with generous style.",byron:"Make space as confidently as you take it."},theme:["#f6a84f","#f8ce96","rgba(246,168,79,.18)"],layout:"solar"},
{id:"virgo",name:"Virgo",glyph:"♍",dates:"AUG 23 — SEP 22",element:"EARTH · MUTABLE",title:"Refine the Take-off",trait:"precise attention",lesson:"Refinement beats perfection when the sea keeps moving.",mantra:{bondi:"Refine one part of your take-off.",byron:"Make one small adjustment, then trust it."},theme:["#b7c789","#d8dfbd","rgba(183,199,137,.18)"],layout:"earth"},
{id:"libra",name:"Libra",glyph:"♎",dates:"SEP 23 — OCT 22",element:"AIR · CARDINAL",title:"Effort Meets Ease",trait:"instinct for balance",lesson:"Find the point where effort and ease meet.",mantra:{bondi:"Share the peak and preserve your rhythm.",byron:"Balance finds the peak."},theme:["#e0a6d7","#edcbe7","rgba(224,166,215,.18)"],layout:"split"},
{id:"scorpio",name:"Scorpio",glyph:"♏",dates:"OCT 23 — NOV 21",element:"WATER · FIXED",title:"Meet Power Calmly",trait:"calm intensity",lesson:"Meet the ocean's force without trying to overpower it.",mantra:{bondi:"Keep your breathing steady.",byron:"Let depth become composure."},theme:["#a783dc","#cdbbea","rgba(167,131,220,.2)"],layout:"lunar"},
{id:"sagittarius",name:"Sagittarius",glyph:"♐",dates:"NOV 22 — DEC 21",element:"FIRE · MUTABLE",title:"A Wider Horizon Calls",trait:"adventurous perspective",lesson:"Exploration works best when respect sets the boundary.",mantra:{bondi:"Leave room for an unexpected line.",byron:"Explore with respect."},theme:["#f0836e","#f5b8ac","rgba(240,131,110,.18)"],layout:"horizon"},
{id:"capricorn",name:"Capricorn",glyph:"♑",dates:"DEC 22 — JAN 19",element:"EARTH · CARDINAL",title:"Patience Builds the Session",trait:"disciplined patience",lesson:"Positioning and persistence will outperform urgency.",mantra:{bondi:"Hold the patient position.",byron:"Build the session one sound decision at a time."},theme:["#8fb8a2","#bdd3c7","rgba(143,184,162,.18)"],layout:"earth"},
{id:"aquarius",name:"Aquarius",glyph:"♒",dates:"JAN 20 — FEB 18",element:"AIR · FIXED",title:"Observe, Then Experiment",trait:"independent imagination",lesson:"Try the unusual line after understanding the ordinary one.",mantra:{bondi:"Look beyond the obvious peak.",byron:"Read the pattern, then break it gently."},theme:["#6eced0","#b0e4e5","rgba(110,206,208,.18)"],layout:"horizon"},
{id:"pisces",name:"Pisces",glyph:"♓",dates:"FEB 19 — MAR 20",element:"WATER · MUTABLE",title:"Dream with Open Eyes",trait:"deep sensitivity",lesson:"Tune into the sea without drifting away from the facts.",mantra:{bondi:"Follow the ocean's tempo.",byron:"Feel the hidden tempo."},theme:["#768fe3","#afbbea","rgba(118,143,227,.2)"],layout:"lunar"}
];
function locationFromData(entry){
  const c=entry.conditions,r=entry.report;
  return {name:r.location,height:Number(c.wave_height_m).toFixed(1),period:String(Math.round(c.primary_period_s)).padStart(2,"0"),wind:c.wind_direction,speed:`${Number(c.wind_speed_m_s).toFixed(1)} m/s · ${c.wind_quality}`,character:c.height_feel,summary:c.ocean_feeling,horoscopes:Object.fromEntries(r.horoscopes.map(h=>[h.sign,h]))};
}
const locations={bondi:locationFromData(window.SURF_DATA["Bondi Beach"]),byron:locationFromData(window.SURF_DATA["Byron Bay"])};
let activeLocation="bondi",activeSign="aries";
const signGrid=document.querySelector("#sign-grid");
signs.forEach((sign,i)=>{const button=document.createElement("button");button.className="sign-button";button.dataset.sign=sign.id;button.setAttribute("role","option");button.setAttribute("aria-selected",sign.id===activeSign);button.innerHTML=`<span class="glyph">${sign.glyph}</span><span class="name">${sign.name.toUpperCase()}</span>`;button.addEventListener("click",()=>{activeSign=sign.id;render()});signGrid.appendChild(button)});
document.querySelectorAll(".location-tab").forEach(button=>button.addEventListener("click",()=>{activeLocation=button.dataset.location;render()}));
signGrid.addEventListener("keydown",event=>{if(!["ArrowRight","ArrowLeft","ArrowDown","ArrowUp"].includes(event.key))return;event.preventDefault();const current=signs.findIndex(sign=>sign.id===activeSign);const step=event.key==="ArrowRight"?1:event.key==="ArrowLeft"?-1:event.key==="ArrowDown"?4:-4;activeSign=signs[(current+step+signs.length)%signs.length].id;render();document.querySelector(`[data-sign="${activeSign}"]`).focus()});
function setText(id,text){document.querySelector(`#${id}`).textContent=text}
function render(){const sign=signs.find(s=>s.id===activeSign),location=locations[activeLocation],reading=location.horoscopes[sign.name],index=signs.indexOf(sign)+1;document.documentElement.style.setProperty("--sign",sign.theme[0]);document.documentElement.style.setProperty("--sign-soft",sign.theme[1]);document.documentElement.style.setProperty("--glow",sign.theme[2]);document.body.dataset.layout=sign.layout;document.querySelectorAll(".location-tab").forEach(b=>{const on=b.dataset.location===activeLocation;b.classList.toggle("active",on);b.setAttribute("aria-selected",on)});document.querySelectorAll(".sign-button").forEach(b=>{const on=b.dataset.sign===activeSign;b.classList.toggle("selected",on);b.setAttribute("aria-selected",on)});setText("sign-index",`${String(index).padStart(2,"0")} / 12`);setText("zodiac-glyph",sign.glyph);setText("element-label",sign.element);setText("location-label",location.name.toUpperCase());setText("sign-dates",sign.dates);setText("reading-title",reading.headline);setText("mantra",reading.surf_intention);setText("reading-copy",reading.reading);setText("conditions-location",location.name);setText("wave-height",location.height);setText("wave-period",location.period);setText("wind-direction",location.wind);setText("wind-speed",location.speed);setText("conditions-note",location.summary)}
render();
